---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

jobs:
  # All tests specified in the `/plans/` subdir
  - job: tests
    trigger: ignore # We use cirrus for now
    skip_build: true
    notifications:
      failure_comment:
        message: "Tests failed. @containers/packit-build please check."
    targets:
      - fedora-latest-stable-x86_64
      - fedora-latest-stable-aarch64
    identifier: build_and_verify
    tmt_plan: "/plans/build_and_verify"
